name: user

msg:
  host: 172.16.0.13
  port: 5672
  username: user
  password: user

postgres:
  host: 172.16.0.11
  port: 5432
  username: postgres
  password: postgres

register:
  host: 172.16.0.14
  port: 6379
  password: redis
  index: 0

validate:
  host: 172.16.0.14
  port: 6379
  password: redis
  index: 1